---
title: "Everglades"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include = FALSE, warning=FALSE}
#### Set-Up ####
# Provide the Bay, Year, and Month for which you'd like to map sites
# all need to be given as character strings (enclosed in quotes)
Estuary = "EV" #provide 2-digit bay code here
Year = "22"    #provide 2-digit year here
Month = "10"   #provide 2-digit month here
# STOP Set-Up
```

```{r prep, include = FALSE, warning=FALSE}
#### Prep Workspace ####
library(DBI)         # for interacting with SQL database
library(dbplyr)      # for interacting with SQL database
library(tidyverse)
library(sf)          # classes and functions for vector data
library(mapview)     # trying this one for interactive map - may also want to look into leaflet
library(leaflet)
library(leafem)
library(htmlwidgets) # to save mapview map as html

# Prep the parts of the title of the map - and file names
FullYear <- paste0("20", Year)
MonthName <- month.name[as.numeric(Month)]

#### Gather sampling site location info ####
# Connect to FIM inshore SQL database
conn <- dbConnect(odbc::odbc(), driver = "SQL Server", 
                  server = "fwc-spsd2",
                  database = "FSAv1",
                  uid = "FIMreader", 
                  pwd = "Read1fish2fish!")

# Gather site location info from the "station" table of FSAV1
stations <- tbl(conn,in_schema("dbo", "tbl_station")) %>% 
  select(Bay, Station_ID, StationDate, Gear, Zone, Subzone, Stratum, Grid, Latitude = Lat, Longitude = Lon,
         Project, PrimaryAlternate, last_updated_date, station_used, temp_trip) %>%
  collect() %>%
  filter(Bay == Estuary,
         substr(Station_ID, 3, 4) == Year,
         substr(Station_ID, 5, 6) == Month,
         Project != "XX") %>%
  #make Gear a factor for plotting on map categorically
  mutate(Gear = as.factor(Gear)) %>%
  #sort the data for used stations first and then by station ID
  arrange(-station_used, Station_ID) %>%
  mutate(Gear_Pr = paste0(Gear, "_", Project)) %>%
  #convert to degrees, decimal minutes for easier output for staff (match hand held GPS)
  #I have kept all decimal places...might want to round for hand held GPS use?
  mutate(Lat_deg = trunc(Latitude),
         Lat_min = round((Latitude - Lat_deg)*60, 5),
         Lon_deg = trunc(Longitude),
         Lon_min = round(abs(Longitude - Lon_deg)*60,5))

# save a list of the stations as a .csv file for future reference
write.csv(stations, paste0(Estuary, "_", FullYear, "_", Month, "_SelectedStations.csv"), row.names = FALSE)

# Convert stations to sf object so we can map them
stations_sf <- stations %>%
  st_as_sf(
    coords = c("Longitude", "Latitude"),
    agr = "constant",
    crs = 4326,                # WGS84 projection, to match the shapefile projection
    stringsAsFactors = FALSE,
    remove = TRUE
  )


# #Read in the shapefile of EV basins
EV_sf <- read_sf(dsn = ".", layer = "basinsv2polygon") %>%
  select(BASIN, geometry) %>%
  # mutate(Zone = case_when(is.na(ZONE) ~ ".",
  #                          TRUE ~ ZONE)) %>%
  # filter(Zone != ".") %>%
  st_make_valid() %>%
  #transform crs to 4326 to match others
  st_transform(crs = 4326)




```

## Viewing sites for: `r Estuary`, `r MonthName`, `r FullYear`

```{r map, echo = FALSE, warning=FALSE}
#### Make Interactive sampling Sites Map ####

# # Make a list of icons. We'll index into it based on name.
# /!\ order of icons MUST BE THE SAME as the order of the factor "MapIcon"
map_icons <- iconList(
  circle_blue <- makeIcon(iconUrl = "https://cdn2.iconfinder.com/data/icons/symbols-8/50/1F535-blue-circle-128.png",
                          iconWidth = 15, iconHeight = 15),
  square_orange <- makeIcon(iconUrl = "https://cdn2.iconfinder.com/data/icons/symbols-8/50/1F7E7-orange-square-128.png",
                          iconWidth = 15, iconHeight = 15),
  circle_red <- makeIcon(iconUrl = "https://cdn2.iconfinder.com/data/icons/symbols-8/50/1F534-red-circle-128.png",
                           iconWidth = 15, iconHeight = 15),
  triangle_green <- makeIcon(iconUrl = "https://www.freeiconspng.com/uploads/green-normal-triangle-png-8.png",
                             iconWidth = 15, iconHeight = 15),
  triangle_pink <- makeIcon(iconUrl = "https://cdn4.iconfinder.com/data/icons/water-waves-design/1470/abstract_triangle_spiral_logo-128.png",
                           iconWidth = 15, iconHeight = 15)
)

# add "MapIcon" column as a factor variable : this will be associated to the icons' list
stations2 <- stations %>%
  mutate(MapIcon = case_when(
      Gear_Pr == "439_EV" ~ "square_orange",
      Gear_Pr == "20_EV"  ~ "circle_red",
      Gear_Pr == "23_EV" ~ "circle_blue",
      Gear_Pr == "300_EV" ~ "triangle_green")) %>%
  mutate(MapIcon = as.factor(MapIcon)) %>%
  mutate(MapIcon = ordered(MapIcon, levels = c("circle_blue", "square_orange", "circle_red", "triangle_green"))) 

# leaflet map with grouped layers so can be toggled on/off
iMap <- stations2 %>% 
  #try adding percentage width to see if will automatically adjust to mobile device size?
  leaflet(width = "100%") %>%
  addProviderTiles('Esri.WorldImagery', group = "Satellite") %>%
  addTiles(group = "OpenStreetMaps") %>%
  # Overlay markers and grids as groups so they can be toggled on/off in controls
  # for some reason, we have to use the 'as.numeric' version of the factor, I don't really know why
  addMarkers(lng = ~ Longitude, lat = ~ Latitude, icon = ~ map_icons[as.numeric(MapIcon)],
             label = ~ paste0(Station_ID),
             # popup = ~ paste0("Station = ", Station_ID,
             #                  #"<br>Latitude = ", Latitude,
             #                  #"<br>Longitude = ", Longitude,
             #                  "<br>Lat_DDM = ", paste0(Lat_deg, "° ", Lat_min),
             #                  "<br>Long_DDM = ", paste0(Lon_deg, "° ", Lon_min),
             #                  "<br>Gear_Project = ", Gear_Pr,
             #                  "<br>Zone = ", Zone,
             #                  "<br>Basin = ", Grid,
             #                  "<br>Stratum = ", Stratum,
             #                  "<br>TempTrip = ", temp_trip),
             group = "Sites") %>%
  addPolygons(data = EV_sf,
              fill = F, weight = 1, color = "white",
              #label = ~ paste0(GRID),
              # popup = ~ paste0("GRID = ", GRID,
              #                "<br>Zone = ", Zone),
              group = "Grids") %>%
  addLegend("bottomright", colors = c("orange", "red", "deepskyblue", "green"),
            labels = c("439_EV", "20_EV", "23_EV", "300_EV"),
            title = paste0(Estuary, " ", FullYear, "-", Month,
                           "<br>Gear & Project"),
            opacity = 8,
            group = "Sites"
  ) %>%
  # Layers control
  addLayersControl(
    baseGroups = c("Satellite", "OpenStreetMaps"),
    overlayGroups = c("Sites", "Grids"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  leafem::addMouseCoordinates() %>%
  addScaleBar() %>%
  addMeasure()
iMap
```